accent = "#ffdd80"
cursor = "#f5e0dc"
foreground = "#e6e6e6"
background = "#262626"
selection_foreground = "#1e1e2e"
selection_background = "#f5e0dc"

color0 = "#6699ff"
color1 = "#66cc66"
color2 = "#a6e3a1"
color3 = "#80e680"
color4 = "#e65c5c"
color5 = "#ffcc66"
color6 = "#66cccc"
color7 = "#606060"
color8 = "#2a2a2a"
color9 = "#404040",
color10 = "#404040"
color11 = "#404040"
color12 = "#404040"
color13 = "#404040"
color14 = "#404040"
color15 = "#404040"
